name: BouncEngine
options:
  bundleIdPrefix: net.bouncengi
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: "5.0"

targets:
  BouncEngine:
    type: application
    platform: iOS
    sources:
      - path: BouncEngine
        excludes:
          - Entitlements.plist
    settings:
      base:
        INFOPLIST_FILE: BouncEngine/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: net.bouncengi.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_ENTITLEMENTS: BouncEngine/Entitlements.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SWIFT_STRICT_CONCURRENCY: minimal
